behaviors:
  My Behavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 32768
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: False
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
      goal_conditioning_type: hyper
      deterministic: False
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
        network_settings:
          normalize: False
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          goal_conditioning_type: hyper
          deterministic: False
      curiosity:
       gamma: 0.99
       strength: 0.5
      gail:
        strength: 0.5
        demo_path: "C:\\Users\\Lenovo\\Desktop\\Csani\\rl\\kocsi\\Assets\\Demonstrations\\demo_0.demo"
    behavioral_cloning:
      strength: 0.3
      demo_path: "C:\\Users\\Lenovo\\Desktop\\Csani\\rl\\kocsi\\Assets\\Demonstrations\\demo_0.demo"
    keep_checkpoints: 5
    checkpoint_interval: 50000
    max_steps: 6000000
    time_horizon: 128
    summary_freq: 50000
    threaded: True